config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "products#index"

  resources :products do
    resources :reviews
    collection do
      get 'usa'
      get 'most_reviews'
      get 'most_recent'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :cost, :origin
  has_many :reviews

  scope :made_in_usa, -> { where(origin: "USA")}

  scope :most_reviews, -> {
    select("products.id, products.name, products.origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    }

    scope :most_recent, -> { order(created_at: :desc).limit(3)}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :content_body, length: { in: 50..250 }
  validates :rating, inclusion: { in: 1..5 }
  validates_presence_of :content_body, :rating
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.paginate(:page => params[:page], :per_page => 9)
  end

  def usa
    @usa_products = Product.made_in_usa
  end

  def most_reviews
    @most_reviews_products = Product.most_reviews
  end

  def most_recent
    @most_recent_products = Product.most_recent
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_paths
  end

    private
    def product_params
      params.require(:product).permit(:name, :cost, :origin)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

private
  def review_params
    params.require(:review).permit(:content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_errors.html.erb
<% if @product.errors.any? %>
  <h3>Oops! Something went wrong. Please fix these errors:</h3>
  <ul>
  <% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SpecialtyFoods</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1"
</head>

<body>
  <div class="container">


    <header class="container">
      <nav class="navbar navbar-default">
        <div class="navbar-header">
          <h1>Marina's Specialty Foods</h1>
          <% if user_signed_in? %>
          <p>Logged in as <strong><%= current_user.username %></strong>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
            <% else %>
            <p> <%= link_to "Sign in", new_user_session_path %> </p>
            <% end %>
          </div>
        </nav>
        </header>
          <div class="">
            <ul>
              <li> <%= link_to "Made in USA", usa_products_path %> </li>
              <li> <%= link_to "Most Reviewed", most_reviews_products_path %> </li>
              <li> <%= link_to "Recently Added", most_recent_products_path %> </li>

            </ul>
          </div>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
  </html>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= render "layouts/form" %>

app/views/products/index.html.erb
<div class="title-container">
  <h2>Products</h2>
</div>

<div class="all_products">
  <% @products.each do |product| %>
  <div class="product">
    <div class="thumbnail">
      <p> <%= link_to product.name, product_path(product) %> </p>
    </div>
  </div>
  <% end %>
</div>

<%= link_to "New Product", new_product_path %>

<%= will_paginate @products %>

app/views/products/most_recent.html.erb
<h2>Most Recent Products</h2>

<ul>
  <% @most_recent_products.each do |product| %>
    <li> <%= link_to product.name, product_path(product) %> </li>
  <% end %>
</ul>


<%= link_to "Return to All Products", products_path %>

app/views/products/most_reviews.html.erb
<h2>Top Three Products Most Reviewed</h2>

<ul>
  <% @most_reviews_products.each do |product| %>
    <li> <%= link_to product.name, product_path(product) %> </li>
  <% end %>
</ul>


<%= link_to "Return to All Products", products_path %>

app/views/products/new.html.erb
<h2>Add New Product</h2>

<% if @product.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
  <%= f.submit %>
  <% end %>

<a href="products#index">Return Home</a>

app/views/products/show.html.erb
<h1> <%= @product.name %></h1>

<h4> Cost: $<%= @product.cost %> </h4>

<h4> Made in: <%= @product.origin %> </h4>


<p><%= link_to "Return to Products", products_path %></p>


<p><%= link_to "Edit", edit_product_path(@product) %></p>

<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>


<h3>Reviews</h3>

<% if @product.reviews.any? %>

    <% @reviews.each do |review| %>
      <h5 class="review_title">Reviewed by: <%= review.user.username %> </h5>
      <p class="review_body">"<%= review.content_body %>" </p>


    <% end %>


  <% else %>
    <p>Be the first to review this product!</p>
<% end %>

    <p><%= link_to "Add Review", new_product_review_path(@product) %></p>

app/views/products/usa.html.erb
<h2>Products Made in USA</h2>

<ul>
  <% @usa_products.each do |product| %>
    <li> <%= link_to product.name, product_path(product) %> </li>
  <% end %>
</ul>


<%= link_to "Return to All Products", products_path %>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :rating, "Rating" %>
  <%= f.number_field :rating, min: 1, max: 5, :required => true  %>
  <br>
  <%= f.label :content_body, "Write Review (50-250 characters)" %>
  <br>
  <%= f.text_area :content_body, cols: 30, rows: 10, :required => true %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h3>Add a review</h3>

<%= render "reviews/form"%>

<%= link_to "Back to #{@product.name}", product_path(@product)%>